export const timeSlots = [
  { "9:00": 0 },
  { "9:30": 0 },
  { "10:00": 0 },
  { "10:30": 0 },
  { "11:00": 0 },
  { "11:30": 0 },
  { "12:00": 0 },
  { "12:30": 0 },
  { "13:00": 0 },
  { "14:00": 0 },
  { "14:00": 0 },
  { "14:30": 0 },
  { "15:00": 0 },
  { "15:30": 0 },
  { "16:00": 0 },
  { "16:30": 0 },
  { "17:00": 0 },
  { "17:30": 0 },
  { "16:00": 0 },
  { "17:00": 0 },
  { "17:30": 0 },
  { "18:00": 0 },
  { "18:30": 0 },
  { "19:00": 0 },
  { "19:30": 0 },
  { "20:00": 0 },
]

export enum AddressType {
  billingAddress = 'billingAddress',
  shippingAddress = 'shippingAddress'
}


export const notifications = [
  { value: "1", label: "Marketing Outreach Emails" },
  { value: "12ss", label: "Appointment Reminder Emails" },
  { value: "123", label: "Stronger together Network" },
  { value: "12d", label: "Transactional Notification Email" },
  { value: "1x23", label: "SMS " },
  { value: "cxc", label: "Push Notifications" },
  { value: "1xxcxc23", label: "Voice " },
  { value: "fdf", label: "Stronger Together Moderator" },
];

export const payloadAddUser = [
  "availability",
  "roles",
  "providerState",
  "yearsOfExperience",
  "specialty",
  "professionalDegree",
  "timezone",
  "displayLanguage",
  "phone",
  "email",
  "preferredLanguage",
  "medicalInfo",
  "title",
  "gender",
  "lastName",
  "firstName",
  "facilities",
  "status",
  "username",
  "groups",
  "npi",
  "externalId",
  "middleName",
  "nickName",
  "pronoun",
  "otherLanguages",
  "notifications",
  "optInStatus",
  "info",
  "isModerator",
  "careGroupMaster",
  "initialAppointmentDoctorId",
  "userPreferences",
  "updateScheduling",
  "dob",
  "address",
  "navigator"
]